name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm --filter organic-ui test run

      - name: Run tests with coverage
        run: pnpm --filter organic-ui test:coverage
        
      - name: Display detailed coverage
        if: always()
        run: |
          echo "📊 Coverage Summary:"
          cat packages/organic-ui/coverage/coverage-summary.json | jq -r '
            .total | 
            "Lines: \(.lines.pct)% (\(.lines.covered)/\(.lines.total))\n" +
            "Statements: \(.statements.pct)% (\(.statements.covered)/\(.statements.total))\n" +
            "Functions: \(.functions.pct)% (\(.functions.covered)/\(.functions.total))\n" +
            "Branches: \(.branches.pct)% (\(.branches.covered)/\(.branches.total))"
          '
